# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		scancodes.py
#		Purpose :	Generate PS/2 tables etc (II)
#		Date :		6th August 2022
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import re 

# *******************************************************************************************
#
#		What we want is a table that maps PS/2 keycodes 00-7F onto SDL Key Codes (SDLK_)
#
#		The program then inverses this and uses it to generate a SDL Key code => PS/2 Keycode
#		table
#
# *******************************************************************************************

import os,re,sys

# *******************************************************************************************
#
#							This is scan code, unshifted, shifted data
#
# *******************************************************************************************

rawPS2data = open("ps2data.txt").read(-1)

fixupTable = []
highCode = 0 
codes = {}

for s in rawPS2data.strip().split("\n"):
	m = re.match("^([0-9A-F]+).*?\\|\\|(.*?)\\|\\|(.*?)$",s)
	assert m is not None,"Bad line "+s
	key = m.group(2)
	keyCode = ord(m.group(2)[0])
	shiftKey = ord(m.group(3)[0]) if m.group(3) != "" else 0
	scanCode = int(m.group(1),16)
	highCode = max(highCode,scanCode)
	if len(key) > 1:
		keyCode = 0
		shiftKey = 0
		if key == "Backspace":
			keyCode = 8
		if key == "Tab":
			keyCode = 9
		if key == "Enter":
			keyCode = 13
		if key == "Space":
			keyCode = 32
		if key == "Esc":
			keyCode = 76

	if shiftKey != 0:
		if (keyCode ^ shiftKey) != 32:
			fixupTable.append(keyCode)
			fixupTable.append(shiftKey)

	codes[scanCode] = { "char":m.group(2),"code":m.group(3),"keycode":keyCode }

print(";\n;\t This file is automatically generated.\n;")
print("ASCIIFromScanCode:")
for i in range(0,144):
	print("\t.byte\t${0:02x} ; ${1:02x} {2}".format(codes[i]["keycode"] if i in codes else 0x00,i,codes[i]["char"] if i in codes else ""))
print("\t.byte\t$FF\n")	
print("ShiftFixTable:\n")
for c in fixupTable:
	print("\t.byte\t${1:02x} ; \"{0}\"".format(chr(c),c))
print("\t.byte\t$FF\n")	
